### ISSUE TITLE
"rebuild.sh" may remove other collections under dellemc

### ISSUE THREAD

**Issue by jagadeeshnv** [ansible-collections/dellemc.sonic#9]
##### SUMMARY

The line "rm -rf /root/.ansible/collections/ansible_collections/dellemc/*" will remove other collections. preferably only sonic to be removed

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by javeedf** [comment]
Removed the file. hence closing the bug
